branch-defaults:
  default:
    environment: null
    group_suffix: null
environment-defaults:
  django-env:
    branch: null
    repository: null
  django-web-env:
    branch: null
    repository: null
global:
  application_name: personal_portfolio
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
